-- AlterTable
ALTER TABLE `Trial` MODIFY `status` ENUM('IN_PROGRESS', 'SUCCESS', 'FAILURE', 'PARTIAL', 'UNDER_EXPOSED', 'OVER_EXPOSED', 'FIRST_LAYER_UNDER_EXPOSED', 'FIRST_LAYER_OVER_EXPOSED') NOT NULL;
